### PR TITLE
chore: remove LICENSE

### PR DESCRIPTION
**Pull request by Stebalien**
It looks like this may be confusing pkg.go.dev's license detection.

### CODE REVIEW

**Comment by Stebalien** [comment]
Note: this leaves LICENSE-MIT and LICENSE-APACHE

**Comment by ribasushi** [comment]
@Stebalien just a random note: when you leave two license files like this, github ends up randomly selecting one of them for the built-in license-link stuff.
I settled on the following after latest changes to pkg.go.dev: single file, has intent, has both licenses, keeps everything happy: https://github.com/ipfs/ipfs-repository-template/blob/master/LICENSE.md

image

**Comment by Stebalien** [comment]
Ah, does that work with https://pkg.go.dev/github.com/ipld/go-car? I removed this because go is displaying a scary "UNKNOWN".

But I assume the SPDX thing may fix it. I'll try that.

**Comment by Stebalien** [comment]
Here: https://github.com/ipld/go-car/pull/59

**Pull request merged**
