### PR TITLE
blockstore: make Finalize return *ReadOnly

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
also @dirkmc

**Comment by mvdan** [comment]
Note that ReadWrite does not have a Close method. If one just wants to write via a blockstore and close the file, it means two steps: Finalize + ReadOnly.Close. A couple of extra lines, but I think it's easy enough.

**Comment by dirkmc** [comment]
I wonder if there's a way to optionally get the read-only blockstore so that the caller doesn't have to explicitly call ro.Close() after calling rw.Finalize(), if there's no error.

Would it make sense to have a separate method to get the read-only blockstore?

**Comment by mvdan** [comment]
What would you call the method that doesn't return a ReadOnly blockstore?

I'd rather not call it Close, because too often people forget to check for its error when writing, e.g. via `defer bs.Close()`.

It might also be a bit confusing to have two slightly different and mutually exclusive "finalize" methods, so I thought a single one would be best. I'm open to ideas though.

**Comment by dirkmc** [comment]
I see where you're coming from.

Maybe have one method called Finalize that just closes the read-write blockstore, and another called ToReadOnly that returns a read-only blockstore (that the client has to close), or something like that?

**Comment by mvdan** [comment]
Actually, this PR is wrong. It returns a ReadOnly blockstore backed by an *os.File, not an mmap, so that's likely not what we want.

**Comment by willscott** [comment]
> Actually, this PR is wrong. It returns a ReadOnly blockstore backed by an *os.File, not an mmap, so that's likely not what we want.

I can look at this but it sounds like i should wait until you take the next refactor

**Comment by mvdan** [comment]
We've agreed that Finalize doesn't need to return a ReadOnly, so this PR is unnecessary :)

**Pull request closed without merging**
