### PR TITLE
add license file so it can be found by go-licenses

### PR DESCRIPTION
**Pull request by bollwyvl**
Thanks for this! I'm trying to package go-ipfs for [conda-forge](
https://github.com/conda-forge/staged-recipes/pull/13904), and this is one of the few modules that doesn't have a discoverable license file.

### CODE REVIEW

**Comment by rvagg** [comment]
They should actually be dual licensed (along with the other packages you're adding this to), so a LICENSE-MIT and LICENSE-APACHE file, like https://github.com/ipld/js-car. Is that going to be a problem for go-licenses?

**Comment by bollwyvl** [comment]
Yes, i think all the magic license tools know how to find `LICENSE-*` just as well, and will bring in both... I saw that root IPFS was doing the dual license thing, but didn't see any reference to that on this repo. With Apache, a project really does have to have the license in the repo and distribute it with source and binaries to comply with the terms.

**Comment by rvagg** [comment]
Yeah, it's a Protocol Labs policy to dual license its original projects, but it's regularly overlooked with some folks considering it _implied_ since it's documented in other places. That's probably not a great idea and getting them in explicitly would be good.

**Comment by Stebalien** [comment]
Replaced with https://github.com/ipld/go-car/pull/57

**Pull request closed without merging**
