### PR TITLE
Add test script for car verify

### PR DESCRIPTION
**Pull request by willscott**

### CODE REVIEW

**Review by mvdan — APPROVED** [review]
SGTM assuming verify prints nothing when it's happy

**Comment by willscott** [comment]
Not to expand scope too much, but here's also a commit to test the filter command.

**Comment by willscott** [comment]
I feel a bit dirty about the need for windows specific line endings. I guess the alternative is that i'd need to have the test figure file embedded in filter.txt split into a separate file, maybe?

**Comment by mvdan** [comment]
It's best to just not let git convert plaintext files to CRLF: https://github.com/mvdan/sh/blob/master/.gitattributes

**Comment by willscott** [comment]
> It's best to just not let git convert plaintext files to CRLF: https://github.com/mvdan/sh/blob/master/.gitattributes

That appears to have worked :+1:

**Pull request merged**
