### PR TITLE
chore: Bump deps.

### PR DESCRIPTION
**Pull request by Jorropo**
We need this [@berty](https://github.com/berty/berty) to bump our IPFS to 0.7.0.

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
sgtm, @hannahhoward ?

**Comment by hannahhoward** [comment]
@Jorropo we just merged a PR to update ipld-prime -- you should probably rebase on master and submit whatever remains

**Review by hannahhoward — CHANGES_REQUESTED** [review]
Hey sorry -- we actually just merged a PR to update IPLD-prime -- why don't you rebase and whatever remains we'll merge.

**Comment by Jorropo** [comment]
> Hey sorry -- we actually just merged a PR to update IPLD-prime -- why don't you rebase and whatever remains we'll merge.

@hannahhoward 
np, the rebase is done. :slightly_smiling_face:

**Comment by Jorropo** [comment]
@hannahhoward is there something missing to merge pls ?

**Comment by moul** [comment]
hi everyone, is there a way we can help?

**Review by rvagg — APPROVED** [review]

**Comment by Jorropo** [comment]
thx

**Pull request merged**
