### PR TITLE
Update v2 to context datastores

### PR DESCRIPTION
**Pull request by arajasek**
DO NOT MERGE till https://github.com/ipld/go-ipld-prime/pull/312 lands, and the dep is updated to the commit in master / a tag

### CODE REVIEW

**Comment by mvdan** [comment]
Landed :) Mind updating?

**Comment by arajasek** [comment]
> Landed :) Mind updating?

Yessir!

**Comment by mvdan** [comment]
Looks like you missed a couple of places? The v2 module has a few internal packages as well.

**Review by mvdan — APPROVED** [review]
Thanks!

**Pull request merged**
