### PR TITLE
v2: stop using a symlink for LICENSE.md

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by masih — APPROVED** [review]
Would removal of LICENSE from root break the v0 godoc ?

**Comment by mvdan** [comment]
It wouldn't break the last v0 release as that's fixed, but it would make any future v0 releases and master non-OSS, which is also a problem.

And it would make GitHub's heuristics think this repo is non-OSS, probably :)

**Comment by masih** [comment]
> It wouldn't break the last v0 release as that's fixed, but it would make any future v0 releases and master non-OSS, which is also a problem.
> 
> And it would make GitHub's heuristics think this repo is non-OSS, probably :)

I am curious then why are we removing the license from v0 at all?

**Comment by mvdan** [comment]
Oh my. Definitely unintended. Second facepalm of the day.

**Pull request merged**
