### PR TITLE
Update usage of merkledag by go-car

### PR DESCRIPTION
**Pull request by willscott**
* this updates to merkledag v0.11 in go-car v1
* it removes direct usage of merkledag from go-car v2

Note that merkledag remains an indirect dependency for v2 via:
```
% go mod why github.com/ipfs/go-merkledag
github.com/ipld/go-car/v2
github.com/ipld/go-car/v2.test
github.com/ipfs/go-unixfsnode
github.com/ipfs/go-unixfsnode/hamt
github.com/ipfs/go-unixfsnode/hamt.test
github.com/ipfs/go-merkledag
```
This usage to generate a sample dag can likely also be removed in the future

### CODE REVIEW

**Comment by masih** [comment]
fixes https://github.com/ipld/go-car/issues/266

**Review by hannahhoward — APPROVED** [review]
LGTM

**Comment by hannahhoward** [comment]
shoudl we merge @willscott or wait for @rvagg ?

**Review by rvagg — APPROVED** [review]

**Comment by rvagg** [comment]
going to merge this and work on the new dependabot updates which overlap

**Pull request merged**
