### PR TITLE
feat: upgrade from go-block-format to go-libipfs/blocks

### PR DESCRIPTION
**Pull request by hacdias**
`go-block-format` is now deprecated: https://github.com/ipfs/go-block-format/pull/37

It seems like other dependencies have to be updated in order for this to work and they will also be incorporated into go-libipfs. I will update this PR once that is the case.

### CODE REVIEW

**Comment by Jorropo** [comment]
@hacdias you just need to `go get github.com/ipfs/go-block-format@latest`, that required to make librairies like `go-ipfs-blockstore` use stubbed `go-block-format`.

**Review by Jorropo — APPROVED** [review]
LGTM

**Comment by willscott** [comment]
tests still seem unhappy

**Comment by Jorropo** [comment]
> tests still seem unhappy

Yeah there is two go.mod files and there were a typo in one of the files. Fixed it.

**Comment by willscott** [comment]
3 even, right?  (v1, v2, and cmd)

**Comment by Jorropo** [comment]
> 3 even, right? (v1, v2, and cmd)

Right, `cmd` imports it's own outdated version of `go-car` tho.

**Comment by hacdias** [comment]
@Jorropo in a perfect world, we would also have updated https://github.com/ipfs/go-merkledag which go-car depends on.

**Comment by Jorropo** [comment]
@hacdias in a perfect world `go-merkledag` and `go-car` would have been migrated to `go-libipfs` :upside_down_face: 

Using stubs is fine, open a PR on https://github.com/ipfs/go-merkledag if you want to update it.

**Pull request merged**
